### ISSUE TITLE
[PO_from_SO] Feedback

### ISSUE THREAD

**Issue by janbec** [it-projects-llc/addons-dev#407]
Hil @ilmir-k 
first impression looks good! Here is my feedback:

## Access to POs from Sale Order smart button
![image](https://user-images.githubusercontent.com/28890800/38878597-9a19c1d4-4261-11e8-84d8-bccfa3cf811e.png)
The lines are not clickable, can they link to the corresponding PO?

## PO Smart Button in SO
![image](https://user-images.githubusercontent.com/28890800/38878899-5697e8a4-4262-11e8-876d-707f41aade7e.png)
make invisible when 0, otherwise you get a view where the create button won't work

## Wizard: Qty to Order compute
![image](https://user-images.githubusercontent.com/28890800/38879614-0ddae95c-4264-11e8-83e4-6087fd4b66ee.png)
Right now, in order to get the qty to order, the qty on hand is used. I think it is better to use qty_forecasted. 

## Qty to order creates a PO
If you have a line in the wizard with qty_to_order = 0 and press create purchase orders, the wizard will create a purchase orders. If qty = 0, no purchase order.

## No Vendor Error Message
![image](https://user-images.githubusercontent.com/28890800/38880099-35d029bc-4265-11e8-98da-d31fc439b1b5.png)
If no vendor is set for the one wizard line, the error message is a general validation error. Can you point the use to the cause of the error?

## Setting a vendor on the wizard line
![image](https://user-images.githubusercontent.com/28890800/38880366-d0fe644e-4265-11e8-8d9b-91f9dfbafe9a.png)
The vendor field should have a domain allowing only entries listed in the supplierinfos. If there is none, nothing should be selectable.

## Not enough inventory message
Can you disable this message and maybe use text-decoration danger for forecasted qty <= 0?
![image](https://user-images.githubusercontent.com/28890800/38881107-9355d7b0-4267-11e8-9c71-d83ad9b19d3b.png)

## Tax on SO line causes Error on opening PO wizard
![image](https://user-images.githubusercontent.com/28890800/38881001-544cde88-4267-11e8-8181-7cb19fa8cb6f.png)
If the tax field on SO line is filled, this error will occur:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/addons/purchase_order_from_so/models/sale_order.py", line 26, in create_purchase_order
    wizard.create_po_lines_from_so(self)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/addons/purchase_order_from_so/wizard/purchase_order_wizard.py", line 84, in create_po_lines_from_so
    'taxes_id': line.tax_id.id,
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/models.py", line 3358, in create
    record = self.browse(self._create(old_vals))
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/models.py", line 3505, in _create
    field.write(self.with_context(rel_context), vals[name], create=True)
  File "/mnt/odoo-extra/runbot/static/build/15668-misc-addons-11-0-purchase-order--cd112f/odoo/fields.py", line 2452, in write
    for act in (value or []):
TypeError: 'int' object is not iterable
```

## Vendor Tax 
If a vendor tax is configured in the product, the wizard will not fill the tax field in wizard or PO.
![image](https://user-images.githubusercontent.com/28890800/38881059-7347d96e-4267-11e8-83d9-0af35fc2ef15.png)
Even if the tax is filled manually in the wizard, it will not be passed to PO.

## Wizard line when enough qty
![image](https://user-images.githubusercontent.com/28890800/38881677-a6347962-4268-11e8-9a75-2f53dad0ed92.png)
If I order a product that has sufficient stock to fullfil the SO, the line will still be red. It should not be red when there is enough stock forecasted.

## Order Ref
![image](https://user-images.githubusercontent.com/28890800/38881775-eb1d92c0-4268-11e8-9e46-39e640d163cd.png)
This field should definietely not be there. Will overwrite the order reference sequence.

## BoM support
I just thought of this but didn't test, the wizard will **not** support Bill of Materials, correct?

**Comment by ilmir-k** [comment]
Hi @janbec
Thanks for the feedback. We are fixing that.

> BoM support
> I just thought of this but didn't test, the wizard will not support Bill of Materials, correct?

Yes, you are correct

**Comment by ilmir-k** [comment]
Hi @janbec

We fixed the issues you noted. Please check the updates:
http://runbot.it-projects.info/runbot/33/misc-addons-11.0-purchase_order_from_so
login and pass: admin

**Comment by ilmir-k** [comment]
Hi @janbec 
It's fixed. Please test the latest updates using the link above.

**Comment by ilmir-k** [comment]
@janbec 
We made the updates. New link for testing:
http://runbot.it-projects.info/runbot/33/419
login and pass: admin

**Comment by janbec** [comment]
awesome, looks good! Nothing to add...
